# Generated by Django 4.1.1 on 2022-11-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom_parts',
            name='bom_id',
        ),
        migrations.AddField(
            model_name='bom_parts',
            name='bom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.boms'),
        ),
    ]
