# Generated by Django 4.1.1 on 2022-10-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'supplier_stock',
            },
        ),
        migrations.DeleteModel(
            name='novo',
        ),
    ]
