# Generated by Django 4.1.1 on 2022-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='django_content_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
