# Generated by Django 4.1.1 on 2022-11-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_purchase',
            name='manufacturers_id',
        ),
        migrations.AddField(
            model_name='part_purchase',
            name='manufacturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.manufacturers'),
        ),
        migrations.AlterField(
            model_name='bom_parts',
            name='part_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.parts'),
        ),
        migrations.AlterField(
            model_name='part_purchase',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.suppliers'),
        ),
    ]
