# Generated by Django 4.1.1 on 2022-11-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0002_remove_bom_parts_bom_id_bom_parts_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.parts'),
        ),
    ]
