# Generated by Django 4.1.1 on 2022-10-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0002_supplier_stock_delete_novo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supplier_stock',
            new_name='SupplierStock',
        ),
        migrations.AlterModelTable(
            name='supplierstock',
            table=None,
        ),
    ]
