# Generated by Django 4.1.1 on 2022-10-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0002_django_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='django_content_type',
        ),
    ]
