# Generated by Django 4.1.1 on 2022-11-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0003_parts_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='part',
        ),
        migrations.RemoveField(
            model_name='supplier_stock',
            name='part_id',
        ),
        migrations.AddField(
            model_name='supplier_stock',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.parts'),
        ),
    ]
