# Generated by Django 4.1.1 on 2022-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0003_rename_supplier_stock_supplierstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.CharField(max_length=150)),
                ('stock', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('part_id', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier_stock',
            },
        ),
        migrations.DeleteModel(
            name='SupplierStock',
        ),
    ]
