# Generated by Django 4.1.1 on 2022-11-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NovoApi_APP', '0004_remove_parts_part_remove_supplier_stock_part_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boms',
            name='board_id',
        ),
        migrations.AddField(
            model_name='boms',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NovoApi_APP.boards'),
        ),
    ]
